Repository contao-community-alliance/contao-multicolumnwizard-bundle, pull requests merged in 2020-03, with the labels that each got.

#71 hide buttons
  README.md
Labels: dokumentation

#65 Replace the class invisible with hidden
  src/Contao/Widgets/MultiColumnWizard.php
Labels: bug

#69 Hotfix css full with for the wizard
  src/Resources/public/css/multicolumnwizard.css
  src/Resources/public/css/multicolumnwizard_src.css
Labels: enhancement

#56 Fix post ajax contao name changes
  src/Contao/Widgets/MultiColumnWizard.php
  src/EventListener/Contao/ExecutePostActions.php
Labels: bug
